[package]
name = "kv-trie"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake2 = "0.10.4"
digest = "0.10.5"
libp2p = {version = "0.48.0"}
serde = "1.0.147"
